# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      run: |
        import requests
        url = 'https://huggingface.co/spaces/tracinginsights/api' # Replace with the URL of the website you want to ping
        url1 = 'https://huggingface.co/spaces/tracinginsights/2018'
        url2 = 'https://huggingface.co/spaces/tracinginsights/2019'
        url3 = 'https://huggingface.co/spaces/tracinginsights/2020'
        url4 = 'https://huggingface.co/spaces/tracinginsights/2021'
        url5 = 'https://huggingface.co/spaces/tracinginsights/2022'
        url6 = 'https://huggingface.co/spaces/tracinginsights/2023'
        response = requests.get(url)
        response1 = requests.get(url1)
        response2 = requests.get(url2)
        response3 = requests.get(url3)
        response4 = requests.get(url4)
        response5 = requests.get(url5)
        response6 = requests.get(url6)
        print(f'Response from {url}: {response.status_code}')
